/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'subject' : string,
  'isPremium' : boolean,
  'createdAt' : Time,
  'description' : string,
  'uploadedBy' : Principal,
  'fileUrl' : [] | [string],
}
export interface PastPaper {
  'id' : string,
  'title' : string,
  'subject' : string,
  'isPremium' : boolean,
  'createdAt' : Time,
  'year' : bigint,
  'description' : string,
  'uploadedBy' : Principal,
  'fileUrl' : string,
}
export interface Question {
  'correctIndex' : bigint,
  'text' : string,
  'options' : Array<string>,
}
export interface Quiz {
  'id' : string,
  'title' : string,
  'subject' : string,
  'questions' : Array<Question>,
}
export interface QuizAttempt {
  'total' : bigint,
  'score' : bigint,
  'timestamp' : Time,
  'quizId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Task {
  'id' : string,
  'title' : string,
  'dueDate' : string,
  'description' : string,
  'isDone' : boolean,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'displayName' : string,
  'isPremium' : boolean,
  'university' : string,
  'course' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTask' : ActorMethod<[string, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createQuiz' : ActorMethod<[string, string, Array<Question>], string>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllPastPapersBySubject' : ActorMethod<[string], Array<PastPaper>>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNoteById' : ActorMethod<[string], Note>,
  'getPastPaperById' : ActorMethod<[string], PastPaper>,
  'getQuizById' : ActorMethod<[string], Quiz>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTasks' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizAttempts' : ActorMethod<[Principal], Array<QuizAttempt>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'postAnswer' : ActorMethod<[string, string], string>,
  'postQuestion' : ActorMethod<[string, string, string], string>,
  'recordQuizAttempt' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTask' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'uploadNote' : ActorMethod<
    [string, string, string, string, [] | [string], boolean],
    string
  >,
  'uploadPastPaper' : ActorMethod<
    [string, string, bigint, string, string, boolean],
    string
  >,
  'upvoteAnswer' : ActorMethod<[string], undefined>,
  'upvoteQuestion' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];